services:
  nav:
    image: ghcr.nju.edu.cn/yingxiaomo/nav:latest
    container_name: nav
    ports:
      - "8642:8642"
    volumes:
      - nav-data:/app/data
    restart: unless-stopped

volumes:
  nav-data:
